services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\JavaScriptRouting\:
        resource: '../../*'
        exclude: '../../{Resources,BecklynJavaScriptRoutingBundle.php}'
