services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $isDebug: '%kernel.debug%'
            $cacheDir: '%kernel.cache_dir%'

    Becklyn\JavaScriptRouting\:
        resource: '../../*'
        exclude: '../../{Resources,BecklynJavaScriptRoutingBundle.php}'

    Becklyn\JavaScriptRouting\Extractor\RoutesExtractor:
        calls:
            - method: setConfigCacheFactory
              arguments:
                  - '@config_cache_factory'
